baseURL: 'https://fbanville.github.io'
languageCode: 'fr-ca'
title: 'Mes projets'
#theme: 'ananke'
theme: 'PaperMod'

menu:
  main:
    - identifier: about
      name: about
      url: about/
    - identifier: meubles
      name: meubles
      url: /tags/meuble
    - identifier: roadtrips
      name: road trips
      url: /tags/roadtrip